server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/authentication
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/authentication
    user: sa
    password: password
  jwt:
    secret: testSecretForJwtTokenGeneratorShouldNotBeUsedAnywhereElseOutsideTests
    lifetime: 30m
logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      example: DEBUG

